### PR TITLE
fix: Proteome comparison: changes similar to circular viewer #1919

### PR DESCRIPTION
**Pull request by maovt**

### CODE REVIEW

**Comment by olsonanl** [comment]
I have deployed this change (cherrypicked into the current service on redwood since the current master has a large rollup of changes pending)

**Comment by maovt** [comment]
Thanks Bob for the quick action. How do I test it?

**Comment by olsonanl** [comment]
Just submit a job; it's updated in the production service

**Comment by maovt** [comment]
Okay. Thanks

**Pull request merged**
