### PR TITLE
New variation service and updates to proteome comparison and RNA-seq

### PR DESCRIPTION
**Pull request by levinas**
Binaries that need to be installed will be sent in email.

### CODE REVIEW

**Comment by levinas** [comment]
This pull request now includes an update to the proteome comparison service:

1. Fix min_ident bug
2. Support new reference types: user_genome, user_feature_group.

**Comment by olsonanl** [comment]
one question - why is DT.pm in the scripts dir and not in lib? I'm thinking the deploy will not do the right thing with it there.
________________________________

**Comment by levinas** [comment]
It was an oversight, and I moved the file.

**Comment by olsonanl** [comment]
I have applied this PR to the https://github.com/olsonanl/app_service repo and deployed on the beta app service. While we're fixing on beta please submit PRs against the olsonanl version (TheSEED version is running on production).

I've turned off the daily update of the production appservice until we are sure this is good to go.

FYI to @brettin

**Pull request merged**
