### PR TITLE
Bug fix: Snp pipeline column 1 does not identify isolates #2146

### PR DESCRIPTION
**Pull request by chmao1**

### CODE REVIEW

**Comment by chmao1** [comment]
This name was defined in the script that was written by the previous author(s).

**Comment by olsonanl** [comment]
OK; this seems fragile as it depends on how this script was invoked. I'll go ahead and merge but we need to thinking about this in a detailed pass through the variation code as a whole.

**Comment by chmao1** [comment]
I noticed that var.snpEff.raw.vcf instead of var.vcf was passed and the same name need to be used to get the sample id.

**Comment by chmao1** [comment]
I agree with you.

**Comment by chmao1** [comment]
Is it ready for testing on production?

**Comment by olsonanl** [comment]
It is now. I went back and added my patches for temp space management into the source tree.

On Nov 9, 2018, at 2:37 PM, chmao1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it ready for testing on production?

**Pull request merged**
